name: Actualizar estadísticas de GitHub

on:
  schedule:
    - cron: "0 6 * * *"  # Ejecuta todos los días a las 6 AM UTC
  workflow_dispatch:      # Permite ejecución manual desde Actions

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Generar estadísticas de GitHub
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=CristianGomez05&show_icons=true&theme=github_dark&hide_border=true&count_private=true"
          curl -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=CristianGomez05&layout=compact&theme=github_dark&hide_border=true"

      - name: Commit y push de los cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats.svg langs.svg
          git commit -m "🔄 Actualizar estadísticas diarias" || echo "Sin cambios para commitear"
          git push
